#!/usr/bin/env python3
"""
HD 产线（多图主体检测 + 抠图 → Gemini 拼版底色 → 横向拼版参考 → 图生图 → 去干扰 → 按 preset 出底图）。

与 run_all_presets 的「单图 + --skip-a4-outpaint」分离；本脚本专用入口需带 -hd。

步骤概览：
  1) 校验 3～5 张输入图与用户 prompt
  2) （可选）Gemini 主体 bbox → BiRefNet 区域抠图（框过小自动改全图）；或 --use-input-as-cutout 跳过抠图、直接以 --images 为 RGBA 抠图；横向拼版（alpha 条带防 scale 爆炸、可用 --layout-* / --layout-preset）
  2b) 中性底拼版草稿 → Gemini 建议纵向渐变底色 + 环境提示 → 正式拼版参考图（Vision 失败即退出，除非跳过开关）
  3) generate_from_description 图生图（-i 参考拼版；默认 --preserve-reference-layout + spec 安全区，约束站位与叠压）
  4) prepare_background：去字/去干扰 + 对齐 preset
  5) （可选）规范主副标题叠字 / 艺术字预览

加 --no-i2i 时在第 2d 步后结束，仅验证抠图与拼版（hd_cutout_*.png、hd_layout_draft_gray.png、hd_layout.png）。

拼版职责划分（重要）：
  - 人物「摆在哪、多大、横纵重叠」全部由本脚本内 _compose_horizontal_layout() 用 Pillow 按规则计算并
    合成；可复现、无额外 Vision 费用。
  - Gemini 不参与几何拼版；仅用于：(a) 可选主体框 detect_subject_bbox；(b) 对灰底草稿 suggest_hd_layout_background
    返回上下渐变 RGB + 一句氛围 hint，供铺底与并入 i2i 描述。
  - 默认新拼版按各图 alpha 内容高度统一缩放（条带/碎 alpha 时用整图高 + scale_cap 防单行过宽）；
    再算横向重叠与脚底对齐；若总跨度超 max_width_ratio 则整行等比缩小。--layout-preset dense_group 等
    只改这些数值参数；dense_group / promo_overlap 使用 center_pyramid 纵向错落（中间角色画布上更靠上，配合绘制顺序显前）。
    promo_overlap 横向重叠更强，更接近商店横版美宣样张。--layout-classic 为旧版「固定间隙横排」。
  - -hd 下默认开启智能拼版（--smart-hd-layout）：单次 Vision 给出左→右顺序与重叠/错落等，本地 clamp；有 spec 安全区时拼版落在该矩形内。
    --no-smart-hd-layout 可关闭。--reuse-cutouts 时 Vision 在已有 hd_cutout_*.png 上运行，只重排拼版顺序、不重编号文件。

示例：
  python scripts/run_hd_line.py -hd \\
    -g "Lengion zone 顶部banner  3840*1200" \\
    --images a.png b.png c.png \\
    --prompt "春日樱花庭院，暖色调" \\
    --hd-style cyber_guofeng \\
    --layout-preset promo_overlap \\
    --output-dir output/hd_line_run1 \\
    -M gemini --packy7s

  # 只跑到拼版、不调 Packy 图生图：
  ... --no-i2i

  # 关闭默认智能拼版（仅当你需要旧行为时）：
  ... --no-smart-hd-layout ...
"""
from __future__ import annotations

import argparse
import json
import math
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# 路径约束验证
from _paths import validate_paths
validate_paths()

EXTRACT_SCRIPT = ROOT / "scripts" / "extract_subject_birefnet.py"
GENERATE_SCRIPT = (
    ROOT
    / ".claude"
    / "skills"
    / "banner-background-from-description"
    / "scripts"
    / "generate_from_description.py"
)
PREPARE_SCRIPT = (
    ROOT
    / ".claude"
    / "skills"
    / "banner-background-from-image"
    / "scripts"
    / "prepare_background.py"
)
COMPOSE_TITLE_ART_SCRIPT = ROOT / "scripts" / "compose_title_art_preview.py"
COMPOSE_BANNER_SCRIPT = (
    ROOT / ".claude" / "skills" / "banner-composer" / "scripts" / "compose_banner.py"
)
GEMINI_SCRIPTS_DIR = (
    ROOT / ".claude" / "skills" / "banner-background-from-image" / "scripts"
)
ENV_FILE = ROOT / ".env"
_SPEC_DIR = ROOT / ".claude" / "skills" / "banner-spec" / "scripts"

_DEFAULT_BG = (245, 245, 248)

# ── 图层 1：抠图完整性检测 ──
_INTEGRITY_CHECK_PROMPT = """Analyze this character cutout image. Check if the following body parts are COMPLETE and VISIBLE:
1. HEAD (including hair, top of head)
2. FACE (eyes, nose, mouth visible)
3. HANDS (both hands, fingers)
4. BODY (torso, clothing)
5. OVERALL completeness

Reply with ONLY a JSON object:
{"head": true/false, "face": true/false, "hands": true/false, "body": true/false, "complete": true/false, "missing": "brief description of what is missing or 'nothing'"}
Output ONLY the JSON, no markdown."""

_INPAINT_CUTOUT_PROMPT = """This is a character cutout with transparent background. The character is missing: {missing_parts}.

Please complete the character by naturally extending/drawing the missing parts in the same art style, lighting, and color palette as the existing parts. Keep the transparent background. Do not change any existing parts of the character.

Output the completed character with the same transparent background."""

# ── 图层 2：生图后人物完整性检测 ──
_I2I_INTEGRITY_PROMPT = """Analyze this horizontal banner image. It was generated by an AI model as a game marketing banner.

Check if ALL characters/subjects in the image are COMPLETE:
1. All heads, faces, hair visible (not cut off by image edges or other objects)
2. All hands, arms, fingers present and naturally connected to body
3. All torsos, clothing complete (no holes, missing sections, or broken anatomy)
4. All legs, feet present (not truncated at bottom edge unless intentionally out of frame)
5. No floating body parts, no dismembered limbs, no anatomy gaps

Reply with ONLY a JSON object:
{"complete": true/false, "issues": "brief description of what is broken/missing/incomplete, or 'none'"}

Output ONLY the JSON, no markdown."""

_I2I_INPAINT_PROMPT = """Fix the following issues in this banner image: {issues}.

Keep the overall composition, colors, style, and background identical. Only fix the specified incomplete or broken character areas. Do NOT change any complete parts of characters. Do NOT add text, watermarks, or UI elements.

Output the fixed banner image at the same resolution."""

# 拼入用户 prompt 后，强调横幅背景、无大字标题（与文生描述 skill 一致方向）
_I2I_LAYOUT_SUFFIX = (
    " 基于参考拼版中的主体布局，生成一张横向游戏/应用商店 Banner 背景图；"
    "三人（或多主体）须处于同一场景、同一透视与光线下，彼此有空间关系（可轻微前后错落或身体朝向呼应），"
    "不要像三张无关贴纸并排；主体群组占据画面大部分宽度，减少两侧大块留白；"
    "主体群组纵向尽量占画面高度约 88%～95%（头顶近上沿、脚底近下沿为宜），勿整体拉远镜头、勿在上下留大块空白天/地；"
    "人物与参考拼版中的相对大小、疏密大致一致，勿明显缩小人群；"
    "人物完整度：每一主体的头颈肩、双臂双手、躯干与双腿须与参考拼版中的轮廓与遮挡关系一致，"
    "衣袖/外套须与肩臂自然相连，禁止断肢、悬浮肢体、肩腋处镂空或与背景错误贯通；"
    "允许为融合场景与魔法/霓虹氛围而自由调整主光、轮廓光、侧逆光、反射与环境光，但勿因此改变姿势或衣形结构；"
    "不要出现大号标题、书法字或 slogan；"
    "风格与上述描述一致，宽屏构图，画面饱满。"
)

# --hd-style：在用户 --prompt 与拼版氛围句之后、_I2I_LAYOUT_SUFFIX 之前追加（none 不追加）
HD_STYLE_EXTRA_PROMPT: dict[str, str] = {
    "none": "",
    "dramatic_group": (
        "影视级横版 Banner：深红与黑色为主的大气背景，身后强逆光与轮廓光，面部有柔和补光；"
        "弥漫烟雾与漂浮火星或微粒，高对比、有戏剧感；"
        "多角色紧密成团、明显前后叠压，中间角色略靠前作视觉锚点，半身或胸像取景，纵向尽量占满；"
        "高精 3D 虚拟偶像或游戏宣发气质，画面中不要生成大屏标题、书法字与 UI 按钮。"
    ),
    "full_group": (
        "构图强化：多人极近身、显著横向重叠，中间略前、两侧略后，同一镜头与同一主光方向；"
        "主体群组在宽度与高度上占画面绝大部分，减少纯色空区；"
        "电影感景深，背景可有体积光、微粒或柔和大气透视，但不要喧宾夺主。"
    ),
    "mountain_toy": (
        "场景：明亮蓝天、远雪顶与蜿蜒山路，奇幻粉绿色植被与可爱小生物或花形元素点缀；"
        "未来潮玩感、虚拟偶像式干净渲染，材质细腻、饱和度受控；"
        "宽画幅、远景层次清晰，人物与环境统一光照与透视。"
    ),
    # Lengion zone / 赛博国风都市夜景美宣背景（可与 --prompt 中角色描写搭配）
    "cyber_guofeng": (
        "深夜或黎明前的东方幻想都市，远处可见传统飞檐与塔楼剪影，近景薄雾与低空云层，"
        "整体深蓝、靛青与黑色为主，留足人物背后的空间层次。"
        "画面充满动感：青蓝色与品红色/洋红的能量碎晶、闪电状光带与粒子轨迹在人物周围盘旋、形成环形动势，"
        "像技能释放或召唤特效；高光对比强，暗部保留细节。"
        "环境光以魔法能量与远处建筑微光为主，人物受轮廓光与侧逆光，气质神秘、战斗感与史诗感并存。"
        "风格为高精度赛博国风游戏美宣插画，笔触干净、边缘利落，无大字标题、无 UI、无水印。"
    ),
}

# --layout-preset dense_group：成团 + 中间略抬高（center_pyramid）+ 较高横向重叠
_LAYOUT_PRESET_DENSE_GROUP: dict[str, float | str] = {
    "fill_height_ratio": 0.90,
    "max_width_ratio": 0.98,
    "overlap_ratio": 0.14,
    "y_stagger_ratio": 0.034,
    "ground_y_ratio": 0.88,
    "stagger_mode": "center_pyramid",
}

# --layout-preset promo_overlap：美宣式强重叠 + 人物纵向顶满（fill 上限 0.95）
_LAYOUT_PRESET_PROMO_OVERLAP: dict[str, float | str] = {
    "fill_height_ratio": 0.95,
    "max_width_ratio": 0.99,
    "overlap_ratio": 0.20,
    "y_stagger_ratio": 0.046,
    "ground_y_ratio": 0.88,
    "stagger_mode": "center_pyramid",
}


def _load_env() -> dict[str, str]:
    result: dict[str, str] = {}
    if not ENV_FILE.is_file():
        return result
    with open(ENV_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                k, v = k.strip(), v.strip().strip("'\"")
                if k and v:
                    result[k] = v
    return result


def _apply_env_to_os(loaded: dict[str, str], use_packy7s: bool, use_packygpt: bool = False, use_micugpt2: bool = False, use_moxingpt: bool = False, use_xingchengpt: bool = False, use_xinchengpt: bool = False) -> None:
    """供当前进程内 Gemini Vision 使用（须先于 import gemini_subject_detect）。"""
    for k, v in loaded.items():
        if k not in os.environ:
            os.environ[k] = v
    if use_moxingpt:
        key = loaded.get("MOXINGPT_API_KEY") or os.environ.get("MOXINGPT_API_KEY", "")
        if key.startswith("sk-"):
            os.environ["MOXINGPT_API_KEY"] = key
            os.environ["BANNER_IMAGE_BACKEND"] = "moxingpt"
        else:
            print(
                "Error: 使用 --moxingpt 时请在 .env 中设置 MOXINGPT_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_xingchengpt:
        key = loaded.get("XINGCHENGGPT_API_KEY") or os.environ.get("XINGCHENGGPT_API_KEY", "")
        if key.startswith("sk-"):
            os.environ["XINGCHENGGPT_API_KEY"] = key
            os.environ["BANNER_IMAGE_BACKEND"] = "xingchengpt"
        else:
            print(
                "Error: 使用 --xingchengpt 时请在 .env 中设置 XINGCHENGGPT_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_xinchengpt:
        key = loaded.get("XINCHENGPT_API_KEY") or os.environ.get("XINCHENGPT_API_KEY", "")
        if key.startswith("sk-"):
            os.environ["XINCHENGPT_API_KEY"] = key
            os.environ["BANNER_IMAGE_BACKEND"] = "xinchengpt"
        else:
            print(
                "Error: 使用 --xinchengpt 时请在 .env 中设置 XINCHENGPT_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_micugpt2:
        key = loaded.get("MICUAPI_API_KEY") or os.environ.get("MICUAPI_API_KEY", "")
        if key.startswith("sk-"):
            os.environ["MICUAPI_API_KEY"] = key
            os.environ["BANNER_IMAGE_BACKEND"] = "micugpt2"
        else:
            print(
                "Error: 使用 --micugpt2 时请在 .env 中设置 MICUAPI_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_packygpt:
        os.environ["GOOGLE_GEMINI_BASE_URL"] = "https://www.packyapi.com"
        key = loaded.get("PACKYGPT_API_KEY") or os.environ.get("PACKYGPT_API_KEY", "")
        if key.startswith("sk-"):
            os.environ["OPENAI_API_KEY"] = key
            os.environ["OPENAI_BASE_URL"] = "https://www.packyapi.com"
            os.environ["OPENAI_MODEL"] = "gpt-image-2"
        else:
            print(
                "Error: 使用 --packygpt 时请在 .env 中设置 PACKYGPT_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_packy7s:
        os.environ["GOOGLE_GEMINI_BASE_URL"] = "https://www.packyapi.com"
        key = loaded.get("PACKY7S_API_KEY") or os.environ.get("PACKY7S_API_KEY", "")
        if key.startswith("sk-"):
            os.environ["GEMINI_API_KEY"] = key


def _make_env(use_packy7s: bool, use_packygpt: bool = False, use_micugpt2: bool = False, use_moxingpt: bool = False, use_xingchengpt: bool = False, use_xinchengpt: bool = False) -> dict:
    env = os.environ.copy()
    loaded = _load_env()
    for k, v in loaded.items():
        if k not in env:
            env[k] = v
    if use_moxingpt:
        key = loaded.get("MOXINGPT_API_KEY") or env.get("MOXINGPT_API_KEY", "")
        if key.startswith("sk-"):
            env["MOXINGPT_API_KEY"] = key
            env["BANNER_IMAGE_BACKEND"] = "moxingpt"
        else:
            print(
                "Error: 使用 --moxingpt 时请在 .env 中设置 MOXINGPT_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_xingchengpt:
        key = loaded.get("XINGCHENGGPT_API_KEY") or env.get("XINGCHENGGPT_API_KEY", "")
        if key.startswith("sk-"):
            env["XINGCHENGGPT_API_KEY"] = key
            env["BANNER_IMAGE_BACKEND"] = "xingchengpt"
        else:
            print(
                "Error: 使用 --xingchengpt 时请在 .env 中设置 XINGCHENGGPT_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_xinchengpt:
        key = loaded.get("XINCHENGPT_API_KEY") or env.get("XINCHENGPT_API_KEY", "")
        if key.startswith("sk-"):
            env["XINCHENGPT_API_KEY"] = key
            env["BANNER_IMAGE_BACKEND"] = "xinchengpt"
        else:
            print(
                "Error: 使用 --xinchengpt 时请在 .env 中设置 XINCHENGPT_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_micugpt2:
        key = loaded.get("MICUAPI_API_KEY") or env.get("MICUAPI_API_KEY", "")
        if key.startswith("sk-"):
            env["MICUAPI_API_KEY"] = key
            env["BANNER_IMAGE_BACKEND"] = "micugpt2"
        else:
            print(
                "Error: 使用 --micugpt2 时请在 .env 中设置 MICUAPI_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_packygpt:
        env["GOOGLE_GEMINI_BASE_URL"] = "https://www.packyapi.com"
        key = loaded.get("PACKYGPT_API_KEY") or env.get("PACKYGPT_API_KEY", "")
        if key.startswith("sk-"):
            env["OPENAI_API_KEY"] = key
            env["OPENAI_BASE_URL"] = "https://www.packyapi.com"
            env["OPENAI_MODEL"] = "gpt-image-2"
        else:
            print(
                "Error: 使用 --packygpt 时请在 .env 中设置 PACKYGPT_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    elif use_packy7s:
        env["GOOGLE_GEMINI_BASE_URL"] = "https://www.packyapi.com"
        key = loaded.get("PACKY7S_API_KEY") or env.get("PACKY7S_API_KEY", "")
        if key.startswith("sk-"):
            env["GEMINI_API_KEY"] = key
        else:
            print(
                "Error: 使用 --packy7s 时请在 .env 中设置 PACKY7S_API_KEY（以 sk- 开头）",
                file=sys.stderr,
            )
            sys.exit(1)
    return env


def _run(cmd: list[str], env: dict | None = None) -> None:
    display = " ".join(f'"{c}"' if " " in c else c for c in cmd)
    print(f"> {display}", flush=True)
    merged_env = (env or os.environ).copy() if isinstance(env, dict) else os.environ.copy()
    merged_env.setdefault("PYTHONUTF8", "1")
    merged_env.setdefault("PYTHONIOENCODING", "utf-8")
    r = subprocess.run(cmd, cwd=str(ROOT), env=merged_env)
    if r.returncode != 0:
        sys.exit(r.returncode)


def _import_spec():
    if str(_SPEC_DIR) not in sys.path:
        sys.path.insert(0, str(_SPEC_DIR))
    import spec

    return spec


def _import_gemini_detect():
    d = str(GEMINI_SCRIPTS_DIR)
    if d not in sys.path:
        sys.path.insert(0, d)
    import gemini_subject_detect as gsd

    return gsd


def _check_and_fix_cutout_integrity(
    cutout_path: Path,
    run_dir: Path,
    index: int,
    total: int,
) -> Path:
    """层1：检测单张抠图主体完整性，残缺则 micugpt2 inpaint 补全。返回最终路径。"""
    gsd = _import_gemini_detect()
    text = gsd._call_micugpt2_vision(str(cutout_path), _INTEGRITY_CHECK_PROMPT)
    if not text:
        print(f"  [HD 2a-ck/{total}] {cutout_path.name} Vision 检测失败，保留原图", flush=True)
        return cutout_path

    start = text.find("{")
    if start < 0:
        print(f"  [HD 2a-ck/{total}] {cutout_path.name} 无法解析 JSON，保留原图", flush=True)
        return cutout_path

    try:
        depth = 0
        for i, c in enumerate(text[start:], start):
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    obj = json.loads(text[start : i + 1])
                    break
        else:
            print(f"  [HD 2a-ck/{total}] {cutout_path.name} JSON 截取失败，保留原图", flush=True)
            return cutout_path
    except (json.JSONDecodeError, UnboundLocalError):
        print(f"  [HD 2a-ck/{total}] {cutout_path.name} JSON 解析失败，保留原图", flush=True)
        return cutout_path

    if obj.get("complete", True):
        body_parts = {k: v for k, v in obj.items() if k in ("head", "face", "hands", "body")}
        flag_str = " ".join(f"{k}={'✓' if v else '✗'}" for k, v in body_parts.items())
        print(f"  [HD 2a-ck/{total}] {cutout_path.name} 完整 ({flag_str})", flush=True)
        return cutout_path

    missing_desc = str(obj.get("missing", "") or "缺失部分")
    body_parts = {k: v for k, v in obj.items() if k in ("head", "face", "hands", "body")}
    flag_str = " ".join(f"{k}={'✓' if v else '✗'}" for k, v in body_parts.items())
    print(f"  [HD 2a-ck/{total}] {cutout_path.name} 残缺 ({flag_str}) — {missing_desc}", flush=True)

    fixed_path = run_dir / f"hd_cutout_fixed_{index:02d}.png"
    inpaint_prompt = _INPAINT_CUTOUT_PROMPT.format(missing_parts=missing_desc)

    prepare_dir = str(PREPARE_SCRIPT.parent)
    if prepare_dir not in sys.path:
        sys.path.insert(0, prepare_dir)
    from prepare_background import _micugpt2_edit_image

    try:
        _micugpt2_edit_image(str(cutout_path), str(fixed_path), inpaint_prompt)
        if fixed_path.is_file() and fixed_path.stat().st_size > 0:
            print(f"  [HD 2a-ck/{total}] 补全完成 -> {fixed_path.name}", flush=True)
            return fixed_path
    except Exception as e:
        print(f"  [HD 2a-ck/{total}] 补全失败 ({e})，保留原图", flush=True)
    return cutout_path


def _check_and_fix_i2i_integrity(
    i2i_path: Path,
    run_dir: Path,
) -> Path:
    """层2：检测图生图输出中的人物完整性，残缺则 micugpt2 inpaint 补全。"""
    gsd = _import_gemini_detect()
    text = gsd._call_micugpt2_vision(str(i2i_path), _I2I_INTEGRITY_PROMPT)
    if not text:
        print("  [HD 3-ck] 图生图 Vision 检测失败，跳过补全", flush=True)
        return i2i_path

    start = text.find("{")
    if start < 0:
        print("  [HD 3-ck] 图生图 Vision 返回非 JSON，跳过补全", flush=True)
        return i2i_path

    try:
        depth = 0
        for i, c in enumerate(text[start:], start):
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    obj = json.loads(text[start : i + 1])
                    break
        else:
            print("  [HD 3-ck] 图生图 JSON 截取失败，跳过补全", flush=True)
            return i2i_path
    except (json.JSONDecodeError, UnboundLocalError):
        print("  [HD 3-ck] 图生图 JSON 解析失败，跳过补全", flush=True)
        return i2i_path

    if obj.get("complete", True):
        print("  [HD 3-ck] 图生图人物完整，跳过补全", flush=True)
        return i2i_path

    issues = str(obj.get("issues", "") or "残缺部位")
    print(f"  [HD 3-ck] 图生图人物残缺: {issues}", flush=True)

    fixed_path = run_dir / "hd_line_i2i_fixed.png"
    inpaint_prompt = _I2I_INPAINT_PROMPT.format(issues=issues)

    prepare_dir = str(PREPARE_SCRIPT.parent)
    if prepare_dir not in sys.path:
        sys.path.insert(0, prepare_dir)
    from prepare_background import _micugpt2_edit_image

    try:
        _micugpt2_edit_image(str(i2i_path), str(fixed_path), inpaint_prompt)
        if fixed_path.is_file() and fixed_path.stat().st_size > 0:
            import shutil as _shutil
            _shutil.copy2(str(fixed_path), str(i2i_path))
            print("  [HD 3-ck] 图生图补全完成，已覆盖原文件", flush=True)
            return i2i_path
    except Exception as e:
        print(f"  [HD 3-ck] 补全失败 ({e})，保留原图", flush=True)
    return i2i_path


def _expand_norm_bbox(
    bbox: tuple[float, float, float, float],
    margin: float = 0.06,
) -> tuple[float, float, float, float]:
    x0, y0, x1, y1 = bbox
    bw, bh = max(1e-6, x1 - x0), max(1e-6, y1 - y0)
    mx, my = bw * margin, bh * margin
    return (
        max(0.0, x0 - mx),
        max(0.0, y0 - my),
        min(1.0, x1 + mx),
        min(1.0, y1 + my),
    )


def _norm_bbox_to_pixel_crop(
    w: int,
    h: int,
    bbox: tuple[float, float, float, float],
) -> tuple[int, int, int, int]:
    x0, y0, x1, y1 = bbox
    x1p = max(0, min(w - 1, math.floor(x0 * w)))
    y1p = max(0, min(h - 1, math.floor(y0 * h)))
    x2p = min(w, max(x1p + 1, math.ceil(x1 * w)))
    y2p = min(h, max(y1p + 1, math.ceil(y1 * h)))
    if x2p <= x1p or y2p <= y1p:
        return 0, 0, w, h
    return x1p, y1p, x2p, y2p


def _vertical_gradient_rgba(
    w: int,
    h: int,
    top: tuple[int, int, int],
    bottom: tuple[int, int, int],
) -> "object":
    from PIL import Image

    try:
        import numpy as np

        fac = np.linspace(1.0, 0.0, h, dtype=np.float32)[:, np.newaxis]
        ta = np.array(top, dtype=np.float32)
        ba = np.array(bottom, dtype=np.float32)
        rows = fac * ta + (1.0 - fac) * ba
        arr = np.tile(rows[:, np.newaxis, :], (1, w, 1))
        arr = np.clip(arr, 0, 255).astype(np.uint8)
        return Image.fromarray(arr, mode="RGB").convert("RGBA")
    except ImportError:
        img = Image.new("RGB", (w, h))
        pix = img.load()
        tr, tg, tb = top
        br, bg_, bb = bottom
        for y in range(h):
            t = y / max(h - 1, 1)
            r = int(round(tr * (1 - t) + br * t))
            g = int(round(tg * (1 - t) + bg_ * t))
            b = int(round(tb * (1 - t) + bb * t))
            for x in range(w):
                pix[x, y] = (r, g, b)
        return img.convert("RGBA")


def _alpha_bbox(im: "object") -> tuple[int, int, int, int]:
    bb = im.split()[-1].getbbox()
    if bb is None:
        return (0, 0, im.size[0], im.size[1])
    return bb


def _compose_horizontal_layout(
    cutout_paths: list[Path],
    canvas_w: int,
    canvas_h: int,
    bg_top: tuple[int, int, int],
    bg_bottom: tuple[int, int, int],
    *,
    layout_classic: bool = False,
    fill_height_ratio: float = 0.82,
    max_width_ratio: float = 0.96,
    overlap_ratio: float = 0.055,
    y_stagger_ratio: float = 0.022,
    ground_y_ratio: float = 0.86,
    stagger_mode: str = "sides_up",
    safe_inner: tuple[int, int, int, int] | None = None,
) -> "object":
    """
    横排拼版（本地几何，非 Gemini）。

    safe_inner：可选 (x_min, y_min, x_max, y_max)，与 spec 安全区一致；人物行的宽高与居中均在该矩形内计算，
    再平移合成到完整 canvas_w×canvas_h 上（左右留白保留给底图）。

    layout_classic=False（默认新逻辑）：
      1) 逐张读入 RGBA，用 alpha getbbox 得内容高度 ch_raw；过矮则用整图高 ch_use 且 scale 封顶 scale_cap，
         使 target_content_h ≈ 内区高 * fill_height_ratio。
      2) 算相邻重叠 overlap_px ≈ mean(width) * overlap_ratio，总跨度 span；若 span > 内区宽 * max_width_ratio
         则对所有层乘同一 factor 缩小。
      3) 纵向：ground_y_ratio 定「地面」线，y = gy - alpha底边 - dy。stagger_mode：
         - sides_up：两侧 dy 大、中间 dy=0（旧版，两侧画布上更靠上）。
         - center_pyramid：中间 dy 最大、两侧小（美宣常见「中间略高、金字塔」+ 配合绘制顺序显前）。
      4) 横向：span 整体水平居中；3 张时绘制顺序 0→2→1，中间最后画、压在两侧之上（显前）。

    layout_classic=True：固定约 62% 内区高、88% 内区宽上限、固定 gap 横排，无重叠与脚底对齐逻辑。
    """
    from PIL import Image

    ims = [Image.open(p).convert("RGBA") for p in cutout_paths]
    if not ims:
        raise RuntimeError("拼版失败：没有有效抠图")

    sx0, sy0 = 0, 0
    vi_w, vi_h = canvas_w, canvas_h
    if safe_inner is not None:
        x0, y0, x1, y1 = safe_inner
        x0 = max(0, min(int(x0), canvas_w - 1))
        y0 = max(0, min(int(y0), canvas_h - 1))
        x1 = max(x0 + 1, min(int(x1), canvas_w))
        y1 = max(y0 + 1, min(int(y1), canvas_h))
        if x1 - x0 >= 64 and y1 - y0 >= 64:
            sx0, sy0, vi_w, vi_h = x0, y0, x1 - x0, y1 - y0

    if layout_classic:
        target_h = int(vi_h * 0.62)
        scaled: list = []
        for im in ims:
            w, h = im.size
            if h <= 0:
                continue
            nh = min(target_h, h)
            nw = max(1, int(w * nh / h))
            scaled.append(im.resize((nw, nh), Image.Resampling.LANCZOS))
        if not scaled:
            raise RuntimeError("拼版失败：没有有效抠图")
        gap = max(12, vi_w // 160)
        total_w = sum(im.size[0] for im in scaled) + gap * (len(scaled) - 1)
        max_allowed = int(vi_w * 0.88)
        if total_w > max_allowed:
            factor = max_allowed / total_w
            scaled = [
                im.resize(
                    (max(1, int(im.size[0] * factor)), max(1, int(im.size[1] * factor))),
                    Image.Resampling.LANCZOS,
                )
                for im in scaled
            ]
            total_w = sum(im.size[0] for im in scaled) + gap * (len(scaled) - 1)
        canvas = _vertical_gradient_rgba(canvas_w, canvas_h, bg_top, bg_bottom)
        max_sc_h = max(im.size[1] for im in scaled)
        x = sx0 + (vi_w - total_w) // 2
        y_base = sy0 + (vi_h - max_sc_h) // 2
        for im in scaled:
            y = y_base + (max_sc_h - im.size[1]) // 2
            canvas.alpha_composite(im, (x, y))
            x += im.size[0] + gap
        return canvas

    # —— 统一主体高度（按 alpha 内容框高度）——
    # 若 ch 极矮（碎块/条带），scale 会爆炸 → 整行超宽 → 统一缩小后人物变成小点；改用整图高并封顶 scale
    fh = max(0.35, min(0.95, float(fill_height_ratio)))
    target_content_h = max(8, int(vi_h * fh))
    alpha_h_min_ratio = 0.12
    scale_cap = 5.0
    scaled = []
    for im in ims:
        w, h = im.size
        if h <= 0:
            continue
        _, y0, _, y1 = _alpha_bbox(im)
        ch_raw = max(1, y1 - y0)
        ch_use = h if ch_raw < max(32, int(h * alpha_h_min_ratio)) else ch_raw
        scale = min(scale_cap, target_content_h / float(ch_use))
        nw = max(1, int(round(w * scale)))
        nh = max(1, int(round(h * scale)))
        scaled.append(im.resize((nw, nh), Image.Resampling.LANCZOS))
    if not scaled:
        raise RuntimeError("拼版失败：没有有效抠图")

    n = len(scaled)
    mw_ratio = max(0.5, min(1.0, float(max_width_ratio)))
    max_span = int(vi_w * mw_ratio)
    ov_r = max(0.0, min(0.35, float(overlap_ratio)))
    widths = [im.size[0] for im in scaled]
    mean_w = sum(widths) / max(len(widths), 1)
    overlap_px = int(round(mean_w * ov_r)) if n > 1 else 0

    def total_span_fn(images: list) -> int:
        if not images:
            return 0
        s = images[0].size[0]
        for j in range(1, len(images)):
            s += images[j].size[0] - overlap_px
        return s

    span = total_span_fn(scaled)
    if span > max_span and span > 0:
        factor = max_span / float(span)
        scaled = [
            im.resize(
                (max(1, int(im.size[0] * factor)), max(1, int(im.size[1] * factor))),
                Image.Resampling.LANCZOS,
            )
            for im in scaled
        ]
        widths = [im.size[0] for im in scaled]
        mean_w = sum(widths) / max(len(widths), 1)
        overlap_px = int(round(mean_w * ov_r)) if n > 1 else 0

    if n > 1 and overlap_px > 0:
        pair_caps = [
            min(scaled[i].size[0], scaled[i + 1].size[0]) - 1 for i in range(n - 1)
        ]
        overlap_px = min(overlap_px, max(0, min(pair_caps)))

    span = total_span_fn(scaled)

    gy = int(vi_h * max(0.55, min(0.94, float(ground_y_ratio))))
    st = max(0.0, min(0.08, float(y_stagger_ratio)))
    mid = (n - 1) / 2.0
    sm = (stagger_mode or "sides_up").strip().lower()
    if sm not in ("sides_up", "center_pyramid"):
        sm = "sides_up"
    max_st_px = int(round(vi_h * st))
    stagger_dys: list[int] = []
    if st <= 0:
        stagger_dys = [0] * n
    elif sm == "center_pyramid":
        max_d = max(abs(i - mid) for i in range(n)) or 1.0
        for i in range(n):
            dist = abs(i - mid)
            factor = 1.0 - (dist / max_d)
            stagger_dys.append(int(round(max_st_px * factor)))
    else:
        for i in range(n):
            dy = int(round(vi_h * st * abs(i - mid) / max(mid, 1e-6)))
            stagger_dys.append(dy)

    foot_bottoms: list[int] = []
    for im in scaled:
        _, _, _, y1a = _alpha_bbox(im)
        foot_bottoms.append(y1a)

    ys: list[int] = []
    for i, im in enumerate(scaled):
        y = gy - foot_bottoms[i] - stagger_dys[i]
        y = max(0, min(y, vi_h - im.size[1]))
        ys.append(sy0 + y)

    x0 = (vi_w - span) // 2
    xs: list[int] = []
    x = sx0 + x0
    for i, im in enumerate(scaled):
        xs.append(x)
        x += im.size[0] - (overlap_px if i < n - 1 else 0)

    canvas = _vertical_gradient_rgba(canvas_w, canvas_h, bg_top, bg_bottom)
    draw_order = list(range(n))
    if n == 3:
        draw_order = [0, 2, 1]
    elif n >= 3:
        mid_i = n // 2
        draw_order = [i for i in range(n) if i != mid_i] + [mid_i]

    for i in draw_order:
        canvas.alpha_composite(scaled[i], (xs[i], ys[i]))
    return canvas


def _detect_pre_cutout(image_path: Path, transparent_ratio_threshold: float = 0.25) -> bool:
    """自动检测图片是否已是干净抠图（含大量透明/半透明像素）。"""
    from PIL import Image

    try:
        im = Image.open(image_path)
    except Exception:
        return False
    if im.mode != "RGBA":
        return False
    try:
        import numpy as np
        arr = np.array(im, dtype=np.uint8)
        alpha = arr[:, :, 3]
        transparent = int(np.sum(alpha == 0))
        semi = int(np.sum((alpha > 0) & (alpha < 255)))
        total = int(alpha.size)
        ratio = (transparent + semi) / max(total, 1)
        return ratio >= transparent_ratio_threshold
    except ImportError:
        # 无 numpy 时逐像素检测（慢但兼容）
        alpha_data = im.getchannel("A")
        pixels = list(alpha_data.getdata())
        total = len(pixels)
        transparent = sum(1 for p in pixels if p == 0)
        semi = sum(1 for p in pixels if 0 < p < 255)
        return (transparent + semi) / max(total, 1) >= transparent_ratio_threshold


def main() -> None:
    parser = argparse.ArgumentParser(
        description="HD 产线：多图抠图拼版 → Gemini 拼版底色 → 图生图 → 去干扰 → preset 底图（须指定 -hd）",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-hd",
        action="store_true",
        dest="hd",
        help="启用 HD 产线（必选；避免与误用 run_all_presets 混淆）",
    )
    parser.add_argument(
        "-g",
        "--genre",
        default=None,
        metavar="NAME",
        help="规范分组：若该组仅含 1 个 preset，则覆盖 --preset（例：LZ顶部banner、Lengion zone 顶部banner  3840*1200）",
    )
    parser.add_argument(
        "--packy7s",
        action="store_true",
        help="显式声明使用 packy7s（默认已启用；与示例命令一致）",
    )
    parser.add_argument(
        "--packygpt",
        "-packygpt",
        action="store_true",
        dest="packygpt",
        help="使用 PackyGPT 专用 key 调用 gpt-image-2（需 .env 中 PACKYGPT_API_KEY）",
    )
    parser.add_argument(
        "--micugpt2",
        "-micugpt2",
        action="store_true",
        dest="micugpt2",
        help="使用 MicuAPI 专用 key 调用 gpt-image-2（需 .env 中 MICUAPI_API_KEY）",
    )
    parser.add_argument(
        "--moxingpt",
        "-moxingpt",
        action="store_true",
        dest="moxingpt",
        help="使用 MoxinGPT 专用 key 调用 gpt-image-2（需 .env 中 MOXINGPT_API_KEY）",
    )
    parser.add_argument(
        "--xingchengpt",
        "-xingchengpt",
        action="store_true",
        dest="xingchengpt",
        help="使用 XingchenGPT 专用 key 调用 gpt-image-2（需 .env 中 XINGCHENGGPT_API_KEY）",
    )
    parser.add_argument(
        "--xinchengpt",
        "-xinchengpt",
        action="store_true",
        dest="xinchengpt",
        help="使用 XinchenGPT 专用 key 调用 gpt-image-2（需 .env 中 XINCHENGPT_API_KEY）",
    )
    parser.add_argument(
        "--images",
        nargs="+",
        required=True,
        metavar="PATH",
        help="3～5 张素材图路径",
    )
    parser.add_argument(
        "--prompt",
        required=True,
        help="画面/风格描述（会与拼版说明拼接后送 i2i）",
    )
    parser.add_argument("--output-dir", "-o", required=True, help="输出目录")
    parser.add_argument(
        "--preset",
        default="legend_top_banner_3840",
        help="目标规格 preset（默认 legend_top_banner_3840）",
    )
    parser.add_argument(
        "--model",
        "-M",
        default="gemini",
        help="图生图模型别名（与 generate_from_description 一致），默认 gemini",
    )
    parser.add_argument(
        "--no-packy7s",
        action="store_true",
        help="关闭 packy7s（默认与其它 LZ 脚本一致：开启 packy7s）",
    )
    parser.add_argument(
        "--skip-remove-text",
        action="store_true",
        help="跳过 prepare 的去字步骤（Gemini remove-text）",
    )
    parser.add_argument(
        "--reuse-cutouts",
        action="store_true",
        help="若输出目录已存在 hd_cutout_00.png …（与 --images 张数一致）则跳过 BiRefNet，直接用于拼版；与 --use-input-as-cutout 互斥",
    )
    parser.add_argument(
        "--use-input-as-cutout",
        action="store_true",
        help="跳过 Gemini 主体框与 BiRefNet，将每张 --images（RGBA，已抠图优先）按顺序写入 hd_cutout_XX.png；与 --reuse-cutouts 互斥；"
        "若仅用 --vision-sort-images 排序请加 --no-smart-hd-layout（-hd 默认智能拼版已含排序）",
    )
    parser.add_argument(
        "--vision-sort-images",
        action="store_true",
        help="Gemini Vision 将 3～5 张素材按画质与横幅适合度重排（左→右，中间为主视觉）；与 --reuse-cutouts 互斥",
    )
    parser.add_argument(
        "--smart-hd-layout",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="-hd 时默认开启：Vision 排序+重叠/错落建议（本地 clamp），有 spec 安全区则拼版落在区内；"
        "--reuse-cutouts 时对已有抠图做 Vision 并重排拼版序；--no-smart-hd-layout 关闭；"
        "与 --vision-sort-images 互斥",
    )
    parser.add_argument(
        "--no-auto-detect-cutout",
        action="store_true",
        dest="no_auto_detect_cutout",
        help="关闭抠图自动检测（默认开启：检测到 RGBA 透明占比 >= 25%% 时自动跳过 BiRefNet 抠图）",
    )
    parser.add_argument(
        "--no-subject-detect",
        action="store_true",
        help="跳过 Gemini 主体框检测，对整图做 BiRefNet 抠图",
    )
    parser.add_argument(
        "--no-gemini-layout-bg",
        action="store_true",
        help="跳过 Gemini 拼版底色建议，使用固定浅灰底",
    )
    parser.add_argument(
        "--no-i2i",
        action="store_true",
        help="跳过图生图及后续（prepare_background、叠字）；仅产出抠图与拼版参考",
    )
    parser.add_argument(
        "--no-i2i-layout-lock",
        action="store_true",
        help="关闭图生图「布局锁定」提示（默认开启：保持参考图站位、疏密、叠压；有 spec 时附带像素安全区）",
    )
    parser.add_argument(
        "--title-art",
        "-t",
        default=None,
        help="可选：透明艺术字 PNG，与底图合成预览",
    )
    parser.add_argument(
        "--compose-main-title",
        default=None,
        metavar="TEXT",
        help="可选：在底图上按 preset 叠主标题（须与 --compose-subtitle 配合或单独使用；no_text 预设不会绘制）",
    )
    parser.add_argument(
        "--compose-subtitle",
        default="",
        metavar="TEXT",
        help="与 --compose-main-title 一起传给 compose_banner",
    )
    parser.add_argument(
        "--compose-output",
        default=None,
        metavar="PATH",
        help="叠字输出路径（默认 output-dir 下 hd_banner_with_text.png）",
    )
    parser.add_argument(
        "--alpha-threshold",
        type=float,
        default=0.5,
        help="BiRefNet 二值化阈值 0~1，默认 0.5",
    )
    parser.add_argument(
        "--hd-check-integrity",
        action="store_true",
        help="S2a 后检测抠图完整性，残缺则 micugpt2 inpaint 补全",
    )
    parser.add_argument(
        "--hd-check-i2i-integrity",
        action="store_true",
        help="S3 后检测图生图人物完整性，残缺则 micugpt2 inpaint 补全",
    )
    parser.add_argument(
        "--hd-style",
        choices=[
            "none",
            "dramatic_group",
            "full_group",
            "mountain_toy",
            "cyber_guofeng",
        ],
        default="none",
        help="追加到图生图的固定风格段落；cyber_guofeng=赛博国风都市夜景美宣背景；默认 none",
    )
    parser.add_argument(
        "--layout-preset",
        choices=["default", "dense_group", "promo_overlap"],
        default="default",
        help="dense_group：约 90%% 主体高+成团；promo_overlap：约 95%% 主体高+强重叠美宣；与 --layout-classic 互斥时以 classic 为准",
    )
    parser.add_argument(
        "--layout-classic",
        action="store_true",
        help="使用旧版拼版（62%% 高、88%% 宽、无重叠与脚底对齐）",
    )
    parser.add_argument(
        "--layout-fill-height",
        type=float,
        default=0.82,
        metavar="R",
        help="拼版：按透明区统一主体高度占画布比例，默认 0.82",
    )
    parser.add_argument(
        "--layout-max-width",
        type=float,
        default=0.96,
        metavar="R",
        help="拼版：人物行最大占画布宽度比例，默认 0.96",
    )
    parser.add_argument(
        "--layout-overlap",
        type=float,
        default=0.055,
        metavar="R",
        help="拼版：相邻层横向重叠占平均宽度比例，默认 0.055；0 关闭",
    )
    parser.add_argument(
        "--layout-stagger",
        type=float,
        default=0.022,
        metavar="R",
        help="拼版：纵向错落幅度（相对画布高），默认 0.022；与 stagger_mode 配合：sides_up 时两侧更靠上，center_pyramid 时中间更靠上；0 关闭",
    )
    parser.add_argument(
        "--layout-ground-y",
        type=float,
        default=0.86,
        metavar="R",
        help="拼版：脚底对齐基准线（纵轴比例，0=顶），默认 0.86",
    )
    args = parser.parse_args()

    if not args.hd:
        parser.error("HD 产线必须指定 -hd，例如: python scripts/run_hd_line.py -hd --images ...")

    if args.smart_hd_layout is None:
        args.smart_hd_layout = True

    if args.smart_hd_layout and args.vision_sort_images:
        parser.error(
            "默认/已开启智能拼版（含 Vision 排序），请勿与 --vision-sort-images 同时使用；"
            "若仅需旧版「只排序」请加 --no-smart-hd-layout --vision-sort-images"
        )

    spec = _import_spec()
    if args.genre:
        gkey = args.genre.strip()
        if gkey not in spec.GENRE_PRESETS:
            print(
                f"Error: 未知分组 {gkey!r}。当前分组: {', '.join(sorted(spec.GENRE_PRESETS))}",
                file=sys.stderr,
            )
            sys.exit(1)
        plist = spec.GENRE_PRESETS[gkey]
        if len(plist) != 1:
            print(
                f"Error: HD 产线 -g 仅支持「恰好 1 个 preset」的分组，{gkey!r} 含 {len(plist)} 个",
                file=sys.stderr,
            )
            sys.exit(1)
        args.preset = plist[0]
    if args.preset not in spec.PRESETS:
        print(f"Error: 未知 preset {args.preset!r}", file=sys.stderr)
        sys.exit(1)
    width, height = spec.PRESETS[args.preset]
    out_filename = spec.OUTPUT_FILENAME_BY_PRESET.get(
        args.preset, f"hd_banner_{width}x{height}.png"
    )

    paths = [Path(p).resolve() for p in args.images]
    for p in paths:
        if not p.is_file():
            print(f"Error: 文件不存在 {p}", file=sys.stderr)
            sys.exit(1)
    if not 3 <= len(paths) <= 5:
        parser.error(f"需要 3～5 张图，当前 {len(paths)} 张")

    if args.use_input_as_cutout and args.reuse_cutouts:
        print(
            "Error: --use-input-as-cutout 与 --reuse-cutouts 互斥。"
            "前者每次从 --images 写入抠图；后者复用目录内已有 hd_cutout_*.png。",
            file=sys.stderr,
        )
        sys.exit(1)

    use_packy7s = not args.no_packy7s
    use_packygpt = getattr(args, "packygpt", False)
    use_micugpt2 = getattr(args, "micugpt2", False)
    use_moxingpt = getattr(args, "moxingpt", False)
    use_xingchengpt = getattr(args, "xingchengpt", False)
    use_xinchengpt = getattr(args, "xinchengpt", False)
    if use_packygpt:
        use_packy7s = False
        args.model = "packygpt"
    if use_micugpt2:
        use_packy7s = False
        args.model = "micugpt2"
    if use_moxingpt:
        use_packy7s = False
        args.model = "moxingpt"
    if use_xingchengpt:
        use_packy7s = False
        args.model = "xingchengpt"
    if use_xinchengpt:
        use_packy7s = False
        args.model = "xinchengpt"
    loaded = _load_env()
    _apply_env_to_os(loaded, use_packy7s, use_packygpt, use_micugpt2, use_moxingpt, use_xingchengpt, use_xinchengpt)
    env = _make_env(use_packy7s, use_packygpt, use_micugpt2, use_moxingpt, use_xingchengpt, use_xinchengpt)

    smart_plan: dict[str, object] | None = None
    # 非复用抠图：先 Vision 排序 paths，再按新顺序抠图，使 hd_cutout_XX 与左→右一致。
    if args.smart_hd_layout and not args.reuse_cutouts:
        gsd_smart = _import_gemini_detect()
        sz_plan = spec.get_safe_zone(width, height, args.preset)
        px0, py0, px1, py1 = (
            (0, 0, width, height) if sz_plan is None else sz_plan
        )
        smart_plan = gsd_smart.vision_plan_hd_banner_layout(
            [str(p) for p in paths],
            canvas_w=width,
            canvas_h=height,
            safe_x_min=px0,
            safe_y_min=py0,
            safe_x_max=px1,
            safe_y_max=py1,
        )
        if smart_plan and isinstance(smart_plan.get("paths"), list):
            paths = [Path(p) for p in smart_plan["paths"]]
            print(
                "[HD] 智能拼版 Vision（左→右）: " + " | ".join(p.name for p in paths),
                flush=True,
            )
        else:
            print(
                "[HD] 智能拼版 Vision 失败，保持 --images 顺序并用下方预设/CLI 拼版参数。",
                flush=True,
            )
            smart_plan = None

    if args.vision_sort_images:
        if args.reuse_cutouts:
            print(
                "Error: --vision-sort-images 与 --reuse-cutouts 不能同用（抠图序号与素材顺序绑定）。"
                "请去掉其一或使用新输出目录且勿带 --reuse-cutouts。",
                file=sys.stderr,
            )
            sys.exit(1)
        gsd_v = _import_gemini_detect()
        sorted_paths = gsd_v.vision_sort_hd_image_layout_order([str(p) for p in paths])
        if sorted_paths:
            paths = [Path(p) for p in sorted_paths]
            print(
                "[HD] Vision 素材排序（左→右）: " + " | ".join(p.name for p in paths),
                flush=True,
            )
        else:
            print(
                "[HD] Vision 素材排序失败，保持 --images 原始顺序。",
                flush=True,
            )

    run_dir = Path(args.output_dir).resolve()
    run_dir.mkdir(parents=True, exist_ok=True)

    gsd = None
    if not args.no_subject_detect or not args.no_gemini_layout_bg:
        gsd = _import_gemini_detect()

    cutouts: list[Path] = []
    for i, src in enumerate(paths):
        co = run_dir / f"hd_cutout_{i:02d}.png"
        if args.reuse_cutouts and co.is_file():
            print(
                f"\n[HD 2a/{len(paths)}] 复用已有抠图 -> {co.name}（--reuse-cutouts）",
                flush=True,
            )
            cutouts.append(co)
            continue
        if not getattr(args, "no_auto_detect_cutout", False) and _detect_pre_cutout(src):
            from PIL import Image as PILImage

            im = PILImage.open(src).convert("RGBA")
            im.save(str(co), "PNG")
            print(
                f"\n[HD 2a/{len(paths)}] 自动识别为干净抠图 -> {co.name}",
                flush=True,
            )
            cutouts.append(co)
            continue
        if args.use_input_as_cutout:
            from PIL import Image as PILImage

            im = PILImage.open(src).convert("RGBA")
            im.save(str(co), "PNG")
            print(
                f"\n[HD 2a/{len(paths)}] 输入图直出抠图 -> {co.name}（--use-input-as-cutout）",
                flush=True,
            )
            cutouts.append(co)
            continue
        cmd_ex: list[str | Path] = [
            sys.executable,
            str(EXTRACT_SCRIPT),
            str(src),
            "--output",
            str(co),
            "--alpha-threshold",
            str(args.alpha_threshold),
        ]
        if not args.no_subject_detect and gsd is not None:
            from PIL import Image as PILImage

            im = PILImage.open(src)
            iw, ih = im.size
            bbox = gsd.detect_subject_bbox(str(src), strict=True, max_retries=3)
            if bbox is None:
                print(
                    f"Error: 主体检测 Vision 失败，已中止（{src.name}）。"
                    "请检查 GEMINI_API_KEY / 网络或加 --no-subject-detect 跳过。",
                    file=sys.stderr,
                )
                sys.exit(1)
            exp = _expand_norm_bbox(bbox)
            x1, y1, x2, y2 = _norm_bbox_to_pixel_crop(iw, ih, exp)
            min_ch = max(64, int(ih * 0.12))
            min_cw = max(64, int(iw * 0.12))
            cw_, ch_ = x2 - x1, y2 - y1
            if cw_ < min_cw or ch_ < min_ch:
                print(
                    f"  [warn] 主体框过小 ({cw_}×{ch_})，改用全图抠图: {src.name}",
                    flush=True,
                )
                x1, y1, x2, y2 = 0, 0, iw, ih
            cmd_ex.extend(["--crop", str(x1), str(y1), str(x2), str(y2)])
            print(
                f"\n[HD 2a/{len(paths)}] 主体框抠图: {src.name} crop=({x1},{y1})-({x2},{y2}) -> {co.name}",
                flush=True,
            )
        else:
            print(f"\n[HD 2a/{len(paths)}] 全图抠图: {src.name} -> {co.name}", flush=True)
        _run(cmd_ex, env=env)
        cutouts.append(co)

    # ── 层 1：抠图完整性检测 + 补全 ──
    if getattr(args, "hd_check_integrity", False):
        n_cut = len(cutouts)
        print(
            f"\n[HD 2a-ck] 抠图完整性检测 ({n_cut} 张)...",
            flush=True,
        )
        fixed: list[Path] = []
        for i, co in enumerate(cutouts):
            fixed.append(_check_and_fix_cutout_integrity(co, run_dir, i, n_cut))
        cutouts = fixed

    # 复用抠图：文件编号固定，仅对已有 hd_cutout_*.png 做 Vision 并重排「拼版用图层顺序」。
    if args.smart_hd_layout and args.reuse_cutouts:
        gsd_smart_r = _import_gemini_detect()
        sz_plan_r = spec.get_safe_zone(width, height, args.preset)
        rx0, ry0, rx1, ry1 = (
            (0, 0, width, height) if sz_plan_r is None else sz_plan_r
        )
        smart_plan = gsd_smart_r.vision_plan_hd_banner_layout(
            [str(c) for c in cutouts],
            canvas_w=width,
            canvas_h=height,
            safe_x_min=rx0,
            safe_y_min=ry0,
            safe_x_max=rx1,
            safe_y_max=ry1,
        )
        if smart_plan and isinstance(smart_plan.get("paths"), list):
            cutouts = [Path(p).resolve() for p in smart_plan["paths"]]
            print(
                "[HD] 智能拼版 Vision（复用抠图，拼版左→右）: "
                + " | ".join(p.name for p in cutouts),
                flush=True,
            )
        else:
            print(
                "[HD] 智能拼版 Vision（复用抠图）失败，按 hd_cutout_00.. 编号顺序拼版。",
                flush=True,
            )
            smart_plan = None

    layout_safe_inner: tuple[int, int, int, int] | None = None
    if args.smart_hd_layout:
        sz_l = spec.get_safe_zone(width, height, args.preset)
        if sz_l is not None:
            layout_safe_inner = sz_l
            print(
                f"\n[HD 2] 拼版几何约束在 spec 安全区内: "
                f"x={sz_l[0]}–{sz_l[1]} y={sz_l[2]}–{sz_l[3]}",
                flush=True,
            )

    if args.layout_classic:
        layout_kw = dict(
            layout_classic=True,
            fill_height_ratio=0.82,
            max_width_ratio=0.96,
            overlap_ratio=0.055,
            y_stagger_ratio=0.022,
            ground_y_ratio=0.86,
        )
    elif smart_plan is not None and not args.layout_classic:
        sm = str(smart_plan.get("stagger_mode") or "center_pyramid")
        if sm not in ("sides_up", "center_pyramid"):
            sm = "center_pyramid"
        layout_kw = dict(
            layout_classic=False,
            fill_height_ratio=max(
                0.35, min(0.95, float(smart_plan["fill_height_ratio"]))
            ),
            max_width_ratio=max(
                0.52, min(1.0, float(smart_plan["max_width_ratio"]))
            ),
            overlap_ratio=max(0.0, min(0.35, float(smart_plan["overlap_ratio"]))),
            y_stagger_ratio=max(
                0.0, min(0.08, float(smart_plan["y_stagger_ratio"]))
            ),
            ground_y_ratio=max(
                0.55, min(0.94, float(smart_plan["ground_y_ratio"]))
            ),
            stagger_mode=sm,
        )
        print(
            f"\n[HD 2] 拼版参数: --smart-hd-layout "
            f"overlap={layout_kw['overlap_ratio']:.3f} "
            f"fill_h={layout_kw['fill_height_ratio']:.3f} "
            f"max_w={layout_kw['max_width_ratio']:.3f} stagger={sm}",
            flush=True,
        )
    elif args.layout_preset == "dense_group":
        d = _LAYOUT_PRESET_DENSE_GROUP
        sm = d.get("stagger_mode", "sides_up")
        if sm not in ("sides_up", "center_pyramid"):
            sm = "sides_up"
        layout_kw = dict(
            layout_classic=False,
            fill_height_ratio=max(0.35, min(0.95, float(d["fill_height_ratio"]))),
            max_width_ratio=max(0.52, min(1.0, float(d["max_width_ratio"]))),
            overlap_ratio=max(0.0, min(0.35, float(d["overlap_ratio"]))),
            y_stagger_ratio=max(0.0, min(0.08, float(d["y_stagger_ratio"]))),
            ground_y_ratio=max(0.55, min(0.94, float(d["ground_y_ratio"]))),
            stagger_mode=sm,
        )
        print(f"\n[HD 2] 拼版参数: layout-preset=dense_group stagger={sm}", flush=True)
    elif args.layout_preset == "promo_overlap":
        d = _LAYOUT_PRESET_PROMO_OVERLAP
        sm = d.get("stagger_mode", "sides_up")
        if sm not in ("sides_up", "center_pyramid"):
            sm = "sides_up"
        layout_kw = dict(
            layout_classic=False,
            fill_height_ratio=max(0.35, min(0.95, float(d["fill_height_ratio"]))),
            max_width_ratio=max(0.52, min(1.0, float(d["max_width_ratio"]))),
            overlap_ratio=max(0.0, min(0.35, float(d["overlap_ratio"]))),
            y_stagger_ratio=max(0.0, min(0.08, float(d["y_stagger_ratio"]))),
            ground_y_ratio=max(0.55, min(0.94, float(d["ground_y_ratio"]))),
            stagger_mode=sm,
        )
        print("\n[HD 2] 拼版参数: layout-preset=promo_overlap (美宣式强重叠+中间抬高)", flush=True)
    else:
        layout_kw = dict(
            layout_classic=False,
            fill_height_ratio=max(0.35, min(0.95, float(args.layout_fill_height))),
            max_width_ratio=max(0.52, min(1.0, float(args.layout_max_width))),
            overlap_ratio=max(0.0, min(0.35, float(args.layout_overlap))),
            y_stagger_ratio=max(0.0, min(0.08, float(args.layout_stagger))),
            ground_y_ratio=max(0.55, min(0.94, float(args.layout_ground_y))),
            stagger_mode="sides_up",
        )

    if args.hd_style != "none":
        print(
            f"\n[HD] 风格预设 hd-style={args.hd_style}（将并入图生图描述）",
            flush=True,
        )

    bg_top = bg_bottom = _DEFAULT_BG
    bg_hint = ""
    draft_path = run_dir / "hd_layout_draft_gray.png"
    print(f"\n[HD 2b] 中性底拼版草稿 -> {draft_path.name}", flush=True)
    draft_img = _compose_horizontal_layout(
        cutouts,
        width,
        height,
        _DEFAULT_BG,
        _DEFAULT_BG,
        safe_inner=layout_safe_inner,
        **layout_kw,
    )
    draft_img.save(str(draft_path))

    if not args.no_gemini_layout_bg and gsd is not None:
        print("\n[HD 2c] Gemini 拼版底色与氛围提示...", flush=True)
        sug = gsd.suggest_hd_layout_background(str(draft_path), args.prompt.strip())
        if not sug:
            print(
                "Error: 拼版底色 Vision 失败（无有效 JSON），已中止。"
                "请检查 GEMINI_API_KEY / 网络或加 --no-gemini-layout-bg 跳过。",
                file=sys.stderr,
            )
            sys.exit(1)
        bg_top = sug["top_rgb"]
        bg_bottom = sug["bottom_rgb"]
        bg_hint = (sug.get("hint") or "").strip()
        print(
            f"  渐变顶 RGB {bg_top} -> 底 RGB {bg_bottom}"
            + (f"；提示: {bg_hint}" if bg_hint else ""),
            flush=True,
        )
    elif args.no_gemini_layout_bg:
        print("\n[HD 2c] 已跳过 Gemini 拼版底色（--no-gemini-layout-bg）", flush=True)

    layout_path = run_dir / "hd_layout.png"
    print(f"\n[HD 2d] 正式拼版参考 -> {layout_path.name}", flush=True)
    layout_img = _compose_horizontal_layout(
        cutouts,
        width,
        height,
        bg_top,
        bg_bottom,
        safe_inner=layout_safe_inner,
        **layout_kw,
    )
    layout_img.save(str(layout_path))

    if args.no_i2i:
        print("\n[HD] 已指定 --no-i2i，跳过图生图及后续步骤。", flush=True)
        print("\nDone（仅拼版）.", flush=True)
        for i, co in enumerate(cutouts):
            print(f"  抠图 {i}: {co}", flush=True)
        print(f"  草稿: {draft_path}", flush=True)
        print(f"  拼版: {layout_path}", flush=True)
        return

    i2i_out = run_dir / "hd_line_i2i.png"
    parts = [args.prompt.strip()]
    style_x = HD_STYLE_EXTRA_PROMPT.get(args.hd_style, "")
    if style_x:
        parts.append(style_x.strip())
    if bg_hint:
        parts.append(f"环境氛围参考：{bg_hint}")
    parts.append(_I2I_LAYOUT_SUFFIX.strip())
    full_prompt = " ".join(p for p in parts if p).strip()

    cmd_gen = [
        sys.executable,
        str(GENERATE_SCRIPT),
        full_prompt,
        str(i2i_out),
        "-W",
        str(width),
        "-H",
        str(height),
        "-i",
        str(layout_path),
        "-M",
        args.model,
    ]
    if use_packy7s:
        cmd_gen.append("--packy")
    sz_i2i = spec.get_safe_zone(width, height, args.preset)
    if not args.no_i2i_layout_lock:
        cmd_gen.append("--preserve-reference-layout")
        if sz_i2i is not None:
            cmd_gen.extend(
                [
                    "--layout-safe-zone",
                    str(sz_i2i[0]),
                    str(sz_i2i[1]),
                    str(sz_i2i[2]),
                    str(sz_i2i[3]),
                ]
            )
        print(
            "\n[HD 3] 图生图（参考拼版，布局锁定：保持站位/疏密/叠压"
            + (
                f"，安全区 x={sz_i2i[0]}–{sz_i2i[1]} y={sz_i2i[2]}–{sz_i2i[3]}"
                if sz_i2i is not None
                else "，当前 preset 无像素安全区条目"
            )
            + "）...",
            flush=True,
        )
    else:
        print("\n[HD 3] 图生图（参考拼版，已关闭布局锁定）...", flush=True)
    _run(cmd_gen, env=env)
    if not i2i_out.is_file():
        print(f"Error: 未产出 {i2i_out}", file=sys.stderr)
        sys.exit(1)

    # ── 层 2：生图后人物完整性检测 + 补全 ──
    if getattr(args, "hd_check_i2i_integrity", False):
        print("\n[HD 3-ck] 图生图人物完整性检测...", flush=True)
        _check_and_fix_i2i_integrity(i2i_out, run_dir)

    final_bg = run_dir / out_filename
    cmd_prep = [
        sys.executable,
        str(PREPARE_SCRIPT),
        str(i2i_out),
        str(final_bg),
        "--preset",
        args.preset,
        "--skip-a4-outpaint",
    ]
    if not args.skip_remove_text:
        cmd_prep.append("--remove-text")
    print("\n[HD 4] prepare_background（去干扰 + 对齐 preset）...", flush=True)
    _run(cmd_prep, env=env)
    if not final_bg.is_file():
        print(f"Error: 未产出底图 {final_bg}", file=sys.stderr)
        sys.exit(1)

    text_out: Path | None = None
    if args.compose_main_title:
        if not COMPOSE_BANNER_SCRIPT.is_file():
            print(f"Error: 未找到 {COMPOSE_BANNER_SCRIPT}", file=sys.stderr)
            sys.exit(1)
        text_out = (
            Path(args.compose_output).resolve()
            if args.compose_output
            else run_dir / "hd_banner_with_text.png"
        )
        cmd_cb = [
            sys.executable,
            str(COMPOSE_BANNER_SCRIPT),
            str(final_bg),
            str(text_out),
            "--main-title",
            args.compose_main_title,
            "--subtitle",
            args.compose_subtitle or "",
            "--preset",
            args.preset,
        ]
        print("\n[HD 5a] compose_banner（规范叠字）...", flush=True)
        _run(cmd_cb, env=env)

    if args.title_art:
        ta = Path(args.title_art).resolve()
        if not ta.is_file():
            print(f"Error: 未找到艺术字 {ta}", file=sys.stderr)
            sys.exit(1)
        base_for_art = text_out if text_out is not None and text_out.is_file() else final_bg
        preview_path = run_dir / (Path(base_for_art).stem + "_title_preview.png")
        cmd_comp = [
            sys.executable,
            str(COMPOSE_TITLE_ART_SCRIPT),
            str(base_for_art),
            str(ta),
            str(preview_path),
            "-p",
            args.preset,
        ]
        print("\n[HD 5b] 合成艺术字预览...", flush=True)
        _run(cmd_comp, env=env)
        print("\nDone.", flush=True)
        print(f"  底图: {final_bg}", flush=True)
        if text_out:
            print(f"  叠字: {text_out}", flush=True)
        print(f"  预览: {preview_path}", flush=True)
    else:
        print("\nDone.", flush=True)
        print(f"  底图: {final_bg}", flush=True)
        if text_out and text_out.is_file():
            print(f"  叠字: {text_out}", flush=True)
        print(f"  拼版: {layout_path}", flush=True)
        print(f"  i2i:  {i2i_out}", flush=True)


if __name__ == "__main__":
    main()
